# Generated by Django 4.0 on 2021-12-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('power', models.PositiveIntegerField()),
                ('engine_type', models.PositiveIntegerField(choices=[(1, 'diesel'), (2, 'benz'), (3, 'electric'), (4, 'other')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('production_year', models.PositiveIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('millage', models.PositiveIntegerField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='examples_app.engine')),
            ],
        ),
    ]
