# Generated by Django 3.2.5 on 2021-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('hide', 'Hide'), ('published', 'Published'), ('new', 'New')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('hide', 'Hide'), ('published', 'Published'), ('new', 'New')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, max_length=355, null=True, unique=True),
        ),
    ]
