# Generated by Django 3.2.5 on 2021-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20211208_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('hide', 'Hide'), ('published', 'Published')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('hide', 'Hide'), ('published', 'Published')], default='new', max_length=20),
        ),
    ]
