# Generated by Django 3.2.5 on 2021-11-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BookModel',
        ),
    ]
